# Generated by Django 2.2 on 2023-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbuy',
            name='image',
            field=models.ImageField(default=2, upload_to='Images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newbuy',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
