# Generated by Django 2.2 on 2023-12-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_auto_20231212_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedbuy',
            name='image',
        ),
    ]
