# Generated by Django 2.2 on 2023-12-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0004_auto_20231213_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='type',
            field=models.CharField(default='new', max_length=200),
            preserve_default=False,
        ),
    ]
